import { TUTORIAL_ID, TUTORIAL_TARGET } from '../ids'
import type { TutorialDefinition } from '../types'

export const MAIN_ONBOARDING: TutorialDefinition = {
  id: TUTORIAL_ID.mainOnboarding,
  version: 1,
  title: 'rInQ Tank kennenlernen',
  steps: [
    {
      id: 'what-is-rink-tank',
      kind: 'explain',
      route: '/',
      placement: 'center',
      title: 'Was ist rInQ Tank?',
      body: 'rInQ Tank ist deine Lern-App für Hockey. Du beobachtest Spiele, beantwortest gezielte Fragen und verstehst Schritt für Schritt mehr.',
      action: { type: 'acknowledge' },
    },
    {
      id: 'home-next-step',
      kind: 'do',
      route: '/',
      targetId: TUTORIAL_TARGET.homeStartT0,
      placement: 'bottom',
      title: 'Dein nächster Schritt',
      body: 'Zuerst kommt Track 0. Tippe auf Track 0 starten. Track A1 geht danach.',
      action: { type: 'click', targetId: TUTORIAL_TARGET.homeStartT0 },
    },
    {
      id: 'setup-explain',
      kind: 'explain',
      route: '/setup/*',
      targetId: TUTORIAL_TARGET.setupMain,
      placement: 'bottom',
      title: 'Hier bereitest du vor',
      body: 'Für Track 0 reicht eine Lektion. Du brauchst kein Spiel und kein Team.',
      action: { type: 'acknowledge' },
    },
    {
      id: 'start-session',
      kind: 'do',
      route: '/setup/*',
      targetId: TUTORIAL_TARGET.setupStart,
      placement: 'top',
      title: 'Lektion starten',
      body: 'Tippe auf Lektion starten. Das ist der echte Button.',
      action: { type: 'route', match: '/session/*' },
      allowPageInteraction: true,
    },
    {
      id: 'session-save',
      kind: 'do',
      route: '/session/*',
      targetId: TUTORIAL_TARGET.sessionAdvance,
      placement: 'top',
      title: 'Lektion machen, dann speichern',
      body: 'Klicke die Übung durch. Session abschließen wird erst aktiv, wenn die Lektion fertig ist.',
      action: { type: 'event', name: 'academy-tutorial-session-completed' },
      allowPageInteraction: true,
    },
    {
      id: 'home-a1',
      kind: 'do',
      route: '/',
      targetId: TUTORIAL_TARGET.homeStartA1,
      placement: 'bottom',
      title: 'Jetzt Track A1',
      body: 'Track 0 ist erledigt. Tippe auf Track A1 starten. Das ist eine echte Beobachtungs-Session.',
      action: { type: 'click', targetId: TUTORIAL_TARGET.homeStartA1 },
    },
    {
      id: 'setup-a1-explain',
      kind: 'explain',
      route: '/setup/*',
      targetId: TUTORIAL_TARGET.setupMain,
      placement: 'bottom',
      title: 'Spiel und Team wählen',
      body: 'Hier legst du fest, welches Spiel und welches Team du beobachtest. Danach startest du die Session.',
      action: { type: 'acknowledge' },
    },
    {
      id: 'start-a1-session',
      kind: 'do',
      route: '/setup/*',
      targetId: TUTORIAL_TARGET.setupStart,
      placement: 'top',
      title: 'Session starten',
      body: 'Tippe auf Session starten. Das ist der echte Button.',
      action: { type: 'route', match: '/session/*' },
      allowPageInteraction: true,
    },
    {
      id: 'session-a1-save',
      kind: 'do',
      route: '/session/*',
      targetId: TUTORIAL_TARGET.sessionAdvance,
      placement: 'top',
      title: 'Session abschließen',
      body: 'Beobachte und beantworte die Frage. Session abschließen wird aktiv, wenn du soweit bist.',
      action: { type: 'event', name: 'academy-tutorial-session-completed' },
      allowPageInteraction: true,
    },
    {
      id: 'history',
      kind: 'show',
      route: '/history',
      targetId: TUTORIAL_TARGET.historyList,
      placement: 'bottom',
      title: 'Dein Verlauf',
      body: 'Abgeschlossene Sessions findest du später hier wieder.',
      action: { type: 'acknowledge' },
      when: { feature: 'history' },
    },
    {
      id: 'locker',
      kind: 'show',
      route: '/locker',
      targetId: TUTORIAL_TARGET.lockerHome,
      placement: 'bottom',
      title: 'Dein Spind',
      body: 'Durch deine Aktivitäten schaltest du Belohnungen und Sammlerstücke frei.',
      action: { type: 'acknowledge' },
      when: { feature: 'locker' },
    },
  ],
}
