export { haversineDistanceMeters, isInsideGeofence, coarseDistanceMeters } from './geofence'
export { getCurrentPositionOnce, readGeolocationPermission, LOCATION_ACCURACY } from './geolocation'
export { isWithinArenaMatchdayWindow, ARENA_MATCHDAY_WINDOW, arenaWindowBounds } from './matchdayWindow'
export { resolveHomeAwayRole } from './homeAway'
export { evaluateVenuePresence, isQualifyingVenueVerification } from './verification'
export { recordVenueVisit, applyVenuePresenceToEvents } from './visits'
export { getDevLocationScenario, setDevLocationScenario, simulateFixForGame } from './devSimulation'
export type { DevLocationScenario } from './devSimulation'
export { readPendingVenuePresence, writePendingVenuePresence, clearPendingVenuePresence } from './presenceCache'
export { sanitizeLocationVerification } from './privacy'
export type { HomeAwayRole } from './homeAway'
export type { GeolocationResult, GeolocationPermissionState } from './geolocation'
