export type RinQIconName =
  | 'observe'
  | 'learn'
  | 'terms'
  | 'mission'
  | 'trophy'
  | 'scene'
  | 'celebrate'
  | 'continue'
  | 'delete'
  | 'shop'
  | 'bolt'
  | 'compass'
  | 'puzzle'
  | 'tools'
  | 'arena'
  | 'home'
  | 'ticket'
  | 'ice'
  | 'ai'
  | 'lock'
  | 'palette'
  | 'coin'
  | 'star'
  | 'starOutline'
  | 'check'
  | 'edit'
  | 'close'
  | 'eye'
  | 'eyeOff'
  | 'film'
  | 'book'
  | 'bus'
  | 'gear'
  | 'folder'
  | 'magnet'

export type RinQIconTone = 'ice' | 'accent' | 'muted' | 'ok' | 'warn' | 'danger'

export type RinQIconSize = 'sm' | 'md' | 'lg'
