import type { AchievementDefinition } from '../types'
import { PHASE2_ACHIEVEMENTS } from './phase2Achievements'

/**
 * Phase-1 achievement catalog (~20). New achievements = data only.
 * Old medal achievements in features/rewards remain for legacy PUX.
 */
export const PHASE1_ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'first_shift',
    name: 'First Shift',
    description: 'Erste echte Academy-Session abschließen.',
    category: 'activity',
    visibility: 'visible',
    rarity: 'common',
    conditions: [{ type: 'event_count', eventType: 'session_completed', target: 1 }],
    rewards: [
      { type: 'xp', amount: 50 },
      { type: 'pux', amount: 25 },
      { type: 'cosmetic', cosmeticId: 'title_first_shift' },
    ],
    progression: { target: 1 },
  },
  {
    id: 'getting_warm',
    name: 'Getting Warm',
    description: '10 echte Sessions abschließen.',
    category: 'activity',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'event_count', eventType: 'session_completed', target: 10 }],
    rewards: [
      { type: 'xp', amount: 150 },
      { type: 'pux', amount: 50 },
    ],
    progression: { target: 10 },
  },
  {
    id: 'rink_rat',
    name: 'Rink Rat',
    description: '50 echte Sessions abschließen.',
    category: 'activity',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'event_count', eventType: 'session_completed', target: 50 }],
    rewards: [
      { type: 'xp', amount: 400 },
      { type: 'pux', amount: 150 },
      { type: 'cosmetic', cosmeticId: 'title_rink_rat' },
    ],
    progression: { target: 50 },
  },
  {
    id: 'first_clip',
    name: 'First Clip',
    description: 'Erste Szene im Szenenpool speichern.',
    category: 'scene_pool',
    visibility: 'visible',
    rarity: 'common',
    conditions: [{ type: 'event_count', eventType: 'scene_created', target: 1 }],
    rewards: [
      { type: 'xp', amount: 40 },
      { type: 'pux', amount: 20 },
    ],
    progression: { target: 1 },
  },
  {
    id: 'clip_goblin',
    name: 'Clip Goblin',
    description: '25 Szenen im Szenenpool speichern.',
    category: 'scene_pool',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'event_count', eventType: 'scene_created', target: 25 }],
    rewards: [
      { type: 'xp', amount: 250 },
      { type: 'pux', amount: 100 },
      { type: 'cosmetic', cosmeticId: 'title_clip_goblin' },
    ],
    progression: { target: 25 },
  },
  {
    id: 'clip_hoarder',
    name: 'Clip Hoarder',
    description: '50 Szenen im Szenenpool speichern.',
    category: 'scene_pool',
    visibility: 'visible',
    rarity: 'epic',
    conditions: [{ type: 'event_count', eventType: 'scene_created', target: 50 }],
    rewards: [
      { type: 'xp', amount: 400 },
      { type: 'pux', amount: 150 },
      { type: 'cosmetic', cosmeticId: 'tagline_one_more_replay' },
    ],
    progression: { target: 50 },
  },
  {
    id: 'thats_going_in',
    name: "That One's Going In",
    description: 'Erste Szene mit 5 Sternen bewerten.',
    category: 'scene_pool',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'field_count', eventType: 'scene_rated', field: 'rating', value: '5', target: 1 }],
    rewards: [
      { type: 'xp', amount: 75 },
      { type: 'pux', amount: 40 },
    ],
    progression: { target: 1 },
  },
  {
    id: 'track_record',
    name: 'Track Record',
    description: 'Ersten Track vollständig abschließen.',
    category: 'curriculum',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'track_completed_count', target: 1 }],
    rewards: [
      { type: 'xp', amount: 200 },
      { type: 'pux', amount: 75 },
      { type: 'cosmetic', cosmeticId: 'title_blue_line_student' },
    ],
    progression: { target: 1 },
  },
  {
    id: 'two_way_student',
    name: 'Two-Way Student',
    description: 'Zwei Tracks vollständig abschließen.',
    category: 'curriculum',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'track_completed_count', target: 2 }],
    rewards: [
      { type: 'xp', amount: 350 },
      { type: 'pux', amount: 120 },
    ],
    progression: { target: 2 },
  },
  {
    id: 'ice_cartographer',
    name: 'Ice Cartographer',
    description: '10 räumliche Rink-Observations (Corridor / Paintable / Path).',
    category: 'mechanics',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [
      {
        type: 'mechanic_usage',
        mechanicId: 'spatial_rink',
        target: 10,
      },
    ],
    rewards: [
      { type: 'xp', amount: 200 },
      { type: 'pux', amount: 80 },
      { type: 'cosmetic', cosmeticId: 'title_ice_cartographer' },
    ],
    progression: { target: 10 },
  },
  {
    id: 'paint_it_black',
    name: 'Paint It Black',
    description: 'Paintable Rink fünfmal nutzen.',
    category: 'mechanics',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'mechanic_usage', mechanicId: 'paintable_rink_observation', target: 5 }],
    rewards: [
      { type: 'xp', amount: 120 },
      { type: 'pux', amount: 50 },
    ],
    progression: { target: 5 },
  },
  {
    id: 'follow_the_arrow',
    name: 'Follow The Arrow',
    description: 'Directional Path fünfmal nutzen.',
    category: 'mechanics',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'mechanic_usage', mechanicId: 'directional_path_observation', target: 5 }],
    rewards: [
      { type: 'xp', amount: 120 },
      { type: 'pux', amount: 50 },
      { type: 'cosmetic', cosmeticId: 'emblem_arrow_unlock' },
    ],
    progression: { target: 5 },
  },
  {
    id: 'five_man_conspiracy',
    name: 'Five-Man Conspiracy',
    description: 'Player-Placement / Formation fünfmal beobachten.',
    category: 'mechanics',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'mechanic_usage', mechanicId: 'defensive_structure', target: 5 }],
    rewards: [
      { type: 'xp', amount: 120 },
      { type: 'pux', amount: 50 },
      { type: 'cosmetic', cosmeticId: 'title_slot_watcher' },
    ],
    progression: { target: 5 },
  },
  {
    id: 'slot_squatter',
    name: 'Slot Squatter',
    description: '8 Sessions mit Defensive-Zone-Fokus.',
    category: 'specialization',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'tag_count', tag: 'defensive_zone', target: 8 }],
    rewards: [
      { type: 'xp', amount: 180 },
      { type: 'pux', amount: 70 },
      { type: 'cosmetic', cosmeticId: 'tagline_no_slot' },
      { type: 'cosmetic', cosmeticId: 'emblem_slot_resident' },
    ],
    progression: { target: 8 },
  },
  {
    id: 'neutral_zone_tourist',
    name: 'Neutral Zone Tourist',
    description: '8 Sessions mit Neutral-Zone-Fokus.',
    category: 'specialization',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'tag_count', tag: 'neutral_zone', target: 8 }],
    rewards: [
      { type: 'xp', amount: 180 },
      { type: 'pux', amount: 70 },
      { type: 'cosmetic', cosmeticId: 'title_neutral_zone_tourist' },
      { type: 'cosmetic', cosmeticId: 'emblem_goblin' },
    ],
    progression: { target: 8 },
  },
  {
    id: 'blue_line_inspector',
    name: 'Blue Line Inspector',
    description: '8 Entry-/Exit-Beobachtungen an der blauen Linie.',
    category: 'specialization',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'tag_count', tag: 'blue_line', target: 8 }],
    rewards: [
      { type: 'xp', amount: 250 },
      { type: 'pux', amount: 100 },
      { type: 'cosmetic', cosmeticId: 'title_blue_line_student' },
      { type: 'cosmetic', cosmeticId: 'emblem_blue_line_inspector' },
    ],
    progression: { target: 8 },
  },
  {
    id: 'scouting_around',
    name: 'Scouting Around',
    description: '5 unterschiedliche Teams analysieren.',
    category: 'teams_leagues',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'unique_count', eventType: 'session_completed', field: 'observedTeamId', target: 5 }],
    rewards: [
      { type: 'xp', amount: 150 },
      { type: 'pux', amount: 60 },
      { type: 'cosmetic', cosmeticId: 'title_puck_detective' },
    ],
    progression: { target: 5 },
  },
  {
    id: 'league_hopper',
    name: 'League Hopper',
    description: '3 unterschiedliche Ligen analysieren.',
    category: 'breadth',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'unique_count', eventType: 'session_completed', field: 'leagueId', target: 3 }],
    rewards: [
      { type: 'xp', amount: 150 },
      { type: 'pux', amount: 60 },
    ],
    progression: { target: 3 },
  },
  {
    id: 'specialist',
    name: 'Specialist',
    description: 'Ersten Special-Teams-Sidequest abschließen.',
    category: 'game_context',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'sidequest_category', category: 'special_teams', target: 1 }],
    rewards: [
      { type: 'xp', amount: 100 },
      { type: 'pux', amount: 50 },
    ],
    progression: { target: 1 },
  },
  {
    id: 'numerical_nonsense',
    name: 'Numerical Nonsense',
    description: 'Erste Numerical Situation analysieren.',
    category: 'game_context',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'sidequest_category', category: 'numerical_situation', target: 1 }],
    rewards: [
      { type: 'xp', amount: 100 },
      { type: 'pux', amount: 50 },
      { type: 'cosmetic', cosmeticId: 'tagline_structure_before_outcome' },
    ],
    progression: { target: 1 },
  },
  {
    id: 'no_idea_yet',
    name: 'No Idea What This Is Yet',
    description: 'Unsicherheit erkennen: 5× „unclear“ als echte Beobachtung.',
    category: 'secret',
    visibility: 'secret',
    rarity: 'epic',
    conditions: [{ type: 'tag_count', tag: 'unclear', target: 5 }],
    rewards: [
      { type: 'xp', amount: 200 },
      { type: 'pux', amount: 80 },
      { type: 'cosmetic', cosmeticId: 'tagline_paused_for_research' },
    ],
    progression: { target: 5 },
  },
]

export const TANK_ACHIEVEMENTS: AchievementDefinition[] = [
  ...PHASE1_ACHIEVEMENTS,
  ...PHASE2_ACHIEVEMENTS,
]

export const TANK_ACHIEVEMENT_BY_ID: Record<string, AchievementDefinition> = Object.fromEntries(
  TANK_ACHIEVEMENTS.map((item) => [item.id, item]),
)

export const ACHIEVEMENT_CATEGORY_LABELS: Record<AchievementDefinition['category'], string> = {
  activity: 'Aktivität',
  curriculum: 'Curriculum',
  specialization: 'Spezialisierung',
  teams_leagues: 'Teams & Ligen',
  game_context: 'Spielkontext',
  scene_pool: 'Szenenpool',
  mechanics: 'Mechaniken',
  breadth: 'Breite',
  depth: 'Tiefe',
  secret: 'Geheim',
}

export function getTankAchievement(id: string): AchievementDefinition | undefined {
  return TANK_ACHIEVEMENT_BY_ID[id]
}
