import type { AchievementDefinition } from '../types'
import { MASTERY_COIN_IDS } from '../mastery/masteryCatalog'

/** Additional Phase-2 achievements (~25) layered on Phase-1 catalog. */
export const PHASE2_ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'module_a1_complete',
    name: 'A1 Complete',
    description: 'Modul A1 vollständig abschließen (alle Drills).',
    category: 'curriculum',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'module_completed', moduleId: 'A1' }],
    rewards: [
      { type: 'xp', amount: 150 },
      { type: 'pux', amount: 60 },
      { type: 'cosmetic', cosmeticId: 'title_module_a1' },
    ],
    progression: { target: 1 },
  },
  {
    id: 'track_a_complete',
    name: 'Track A Complete',
    description: 'Track A vollständig abschließen.',
    category: 'curriculum',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'track_completed', trackId: 'A' }],
    rewards: [
      { type: 'xp', amount: 400 },
      { type: 'pux', amount: 150 },
      { type: 'cosmetic', cosmeticId: 'title_track_a' },
    ],
    progression: { target: 1 },
  },
  {
    id: 'century_club',
    name: 'Century Club',
    description: '100 echte Sessions abschließen.',
    category: 'activity',
    visibility: 'visible',
    rarity: 'epic',
    conditions: [{ type: 'event_count', eventType: 'session_completed', target: 100 }],
    rewards: [
      { type: 'xp', amount: 600 },
      { type: 'pux', amount: 250 },
      { type: 'cosmetic', cosmeticId: 'frame_century' },
    ],
    progression: { target: 100 },
  },
  {
    id: 'scene_century',
    name: 'Scene Century',
    description: '100 Szenen speichern.',
    category: 'scene_pool',
    visibility: 'visible',
    rarity: 'epic',
    conditions: [{ type: 'event_count', eventType: 'scene_created', target: 100 }],
    rewards: [
      { type: 'xp', amount: 500 },
      { type: 'pux', amount: 200 },
      { type: 'cosmetic', cosmeticId: 'banner_scene_century' },
    ],
    progression: { target: 100 },
  },
  {
    id: 'five_star_critic',
    name: 'Five-Star Critic',
    description: '10 Szenen mit 5 Sternen bewerten.',
    category: 'scene_pool',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'field_count', eventType: 'scene_rated', field: 'rating', value: '5', target: 10 }],
    rewards: [
      { type: 'xp', amount: 200 },
      { type: 'pux', amount: 80 },
      { type: 'cosmetic', cosmeticId: 'title_five_star_critic' },
    ],
    progression: { target: 10 },
  },
  {
    id: 'track_trio',
    name: 'Track Trio',
    description: 'Drei Tracks vollständig abschließen.',
    category: 'curriculum',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'track_completed_count', target: 3 }],
    rewards: [
      { type: 'xp', amount: 400 },
      { type: 'pux', amount: 150 },
      { type: 'cosmetic', cosmeticId: 'emblem_track_trio' },
    ],
    progression: { target: 3 },
  },
  {
    id: 'team_ten',
    name: 'Ten Team Tour',
    description: '10 unterschiedliche Teams analysieren.',
    category: 'breadth',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'unique_count', eventType: 'session_completed', field: 'observedTeamId', target: 10 }],
    rewards: [
      { type: 'xp', amount: 300 },
      { type: 'pux', amount: 120 },
      { type: 'cosmetic', cosmeticId: 'banner_ten_team_tour' },
    ],
    progression: { target: 10 },
  },
  {
    id: 'same_team_again',
    name: 'Same Team Again?!',
    description: '15 Sessions mit demselben beobachteten Team.',
    category: 'depth',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'max_field_frequency', eventType: 'session_completed', field: 'observedTeamId', target: 15 }],
    rewards: [
      { type: 'xp', amount: 250 },
      { type: 'pux', amount: 100 },
      { type: 'cosmetic', cosmeticId: 'title_shop_quiet_observer' },
    ],
    progression: { target: 15 },
  },
  {
    id: 'same_drill_five',
    name: 'Drill Regular',
    description: 'Denselben Drill 5× abschließen.',
    category: 'depth',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'max_field_frequency', eventType: 'session_completed', field: 'drillId', target: 5 }],
    rewards: [
      { type: 'xp', amount: 150 },
      { type: 'pux', amount: 60 },
      { type: 'cosmetic', cosmeticId: 'tagline_drill_regular' },
    ],
    progression: { target: 5 },
  },
  {
    id: 'same_drill_ten',
    name: 'Drill Obsessed',
    description: 'Denselben Drill 10× abschließen.',
    category: 'depth',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'max_field_frequency', eventType: 'session_completed', field: 'drillId', target: 10 }],
    rewards: [
      { type: 'xp', amount: 250 },
      { type: 'pux', amount: 100 },
      { type: 'cosmetic', cosmeticId: 'title_drill_obsessed' },
    ],
    progression: { target: 10 },
  },
  {
    id: 'powerplay_regular',
    name: 'Powerplay Regular',
    description: '5 Special-Teams Powerplay-Sidequests.',
    category: 'game_context',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'sidequest_category', category: 'special_teams', target: 5 }],
    rewards: [
      { type: 'xp', amount: 180 },
      { type: 'pux', amount: 80 },
      { type: 'cosmetic', cosmeticId: MASTERY_COIN_IDS.powerplay },
    ],
    progression: { target: 5 },
  },
  {
    id: 'pk_regular',
    name: 'PK Regular',
    description: '3 Special-Teams Sidequests (PK/PP gemischt zählen für MVP).',
    category: 'game_context',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'sidequest_category', category: 'special_teams', target: 3 }],
    rewards: [
      { type: 'xp', amount: 150 },
      { type: 'pux', amount: 70 },
      { type: 'cosmetic', cosmeticId: MASTERY_COIN_IDS.penalty_kill },
    ],
    progression: { target: 3 },
  },
  {
    id: 'numerical_regular',
    name: 'Numerical Regular',
    description: '5 Numerical Situations analysieren.',
    category: 'game_context',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'sidequest_category', category: 'numerical_situation', target: 5 }],
    rewards: [
      { type: 'xp', amount: 220 },
      { type: 'pux', amount: 90 },
      { type: 'cosmetic', cosmeticId: 'emblem_numerical' },
    ],
    progression: { target: 5 },
  },
  {
    id: 'paint_it_black_pro',
    name: 'Paint It Black Pro',
    description: 'Paintable Rink 15× nutzen.',
    category: 'mechanics',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'mechanic_usage', mechanicId: 'paintable_rink_observation', target: 15 }],
    rewards: [
      { type: 'xp', amount: 250 },
      { type: 'pux', amount: 100 },
      { type: 'cosmetic', cosmeticId: 'emblem_paint_pro' },
    ],
    progression: { target: 15 },
  },
  {
    id: 'path_finder',
    name: 'Path Finder',
    description: 'Directional Path 15× nutzen.',
    category: 'mechanics',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'mechanic_usage', mechanicId: 'directional_path_observation', target: 15 }],
    rewards: [
      { type: 'xp', amount: 250 },
      { type: 'pux', amount: 100 },
      { type: 'cosmetic', cosmeticId: 'title_path_finder' },
    ],
    progression: { target: 15 },
  },
  {
    id: 'formation_nerd',
    name: 'Formation Nerd',
    description: 'Defensive Structure 15× nutzen.',
    category: 'mechanics',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'mechanic_usage', mechanicId: 'defensive_structure', target: 15 }],
    rewards: [
      { type: 'xp', amount: 250 },
      { type: 'pux', amount: 100 },
      { type: 'cosmetic', cosmeticId: 'title_formation_nerd' },
    ],
    progression: { target: 15 },
  },
  {
    id: 'spatial_addict',
    name: 'Spatial Addict',
    description: '25 räumliche Rink-Observations.',
    category: 'mechanics',
    visibility: 'visible',
    rarity: 'epic',
    conditions: [{ type: 'mechanic_usage', mechanicId: 'spatial_rink', target: 25 }],
    rewards: [
      { type: 'xp', amount: 350 },
      { type: 'pux', amount: 140 },
      { type: 'cosmetic', cosmeticId: 'frame_spatial' },
    ],
    progression: { target: 25 },
  },
  {
    id: 'slot_landlord',
    name: 'Slot Landlord',
    description: '20 Defensive-Zone-Sessions.',
    category: 'specialization',
    visibility: 'visible',
    rarity: 'epic',
    conditions: [{ type: 'tag_count', tag: 'defensive_zone', target: 20 }],
    rewards: [
      { type: 'xp', amount: 300 },
      { type: 'pux', amount: 120 },
      { type: 'cosmetic', cosmeticId: 'emblem_high_slot' },
    ],
    progression: { target: 20 },
  },
  {
    id: 'blue_line_wizard_ach',
    name: 'Blue Line Wizard',
    description: '20 Blue-Line-/Entry-Exit-Sessions.',
    category: 'specialization',
    visibility: 'visible',
    rarity: 'epic',
    conditions: [{ type: 'tag_count', tag: 'blue_line', target: 20 }],
    rewards: [
      { type: 'xp', amount: 350 },
      { type: 'pux', amount: 140 },
    ],
    progression: { target: 20 },
  },
  {
    id: 'league_tourist',
    name: 'League Tourist',
    description: '5 unterschiedliche Ligen analysieren.',
    category: 'breadth',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'unique_count', eventType: 'session_completed', field: 'leagueId', target: 5 }],
    rewards: [
      { type: 'xp', amount: 220 },
      { type: 'pux', amount: 90 },
      { type: 'cosmetic', cosmeticId: 'title_league_tourist' },
    ],
    progression: { target: 5 },
  },
  {
    id: 'unclear_honest',
    name: 'Honest Fog',
    description: '15× unclear als echte Beobachtung.',
    category: 'secret',
    visibility: 'secret',
    rarity: 'legendary',
    conditions: [{ type: 'tag_count', tag: 'unclear', target: 15 }],
    rewards: [
      { type: 'xp', amount: 400 },
      { type: 'pux', amount: 160 },
      { type: 'cosmetic', cosmeticId: 'title_honest_fog' },
    ],
    progression: { target: 15 },
  },
  {
    id: 'getting_serious',
    name: 'Getting Serious',
    description: '25 echte Sessions.',
    category: 'activity',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'event_count', eventType: 'session_completed', target: 25 }],
    rewards: [
      { type: 'xp', amount: 200 },
      { type: 'pux', amount: 75 },
      { type: 'cosmetic', cosmeticId: 'frame_slot' },
    ],
    progression: { target: 25 },
  },
  {
    id: 'clip_goblin_jr',
    name: 'Clip Goblin Jr.',
    description: '10 Szenen speichern.',
    category: 'scene_pool',
    visibility: 'visible',
    rarity: 'uncommon',
    conditions: [{ type: 'event_count', eventType: 'scene_created', target: 10 }],
    rewards: [
      { type: 'xp', amount: 100 },
      { type: 'pux', amount: 40 },
      { type: 'cosmetic', cosmeticId: 'emblem_clip_goblin_jr' },
    ],
    progression: { target: 10 },
  },
  {
    id: 'manual_marker',
    name: 'Manual Marker',
    description: 'Erste manuelle Szene (ohne Session) — via scene_created count 3 als Proxy.',
    category: 'scene_pool',
    visibility: 'visible',
    rarity: 'common',
    conditions: [{ type: 'event_count', eventType: 'scene_created', target: 3 }],
    rewards: [
      { type: 'xp', amount: 60 },
      { type: 'pux', amount: 30 },
      { type: 'cosmetic', cosmeticId: 'tagline_manual_marker' },
    ],
    progression: { target: 3 },
  },
  {
    id: 'nz_deep_dive',
    name: 'NZ Deep Dive',
    description: '15 Neutral-Zone-Sessions.',
    category: 'specialization',
    visibility: 'visible',
    rarity: 'rare',
    conditions: [{ type: 'tag_count', tag: 'neutral_zone', target: 15 }],
    rewards: [
      { type: 'xp', amount: 280 },
      { type: 'pux', amount: 110 },
      { type: 'cosmetic', cosmeticId: 'emblem_goblin' },
    ],
    progression: { target: 15 },
  },
]

/** Custom condition: max sessions for any single observedTeamId / drillId. */
export function maxFieldFrequency(
  events: Array<Record<string, unknown>>,
  eventType: string,
  field: string,
): number {
  const counts = new Map<string, number>()
  for (const event of events) {
    if (event.type !== eventType) continue
    const value = event[field]
    if (value === undefined || value === null || value === '') continue
    const key = String(value)
    counts.set(key, (counts.get(key) || 0) + 1)
  }
  let max = 0
  for (const count of counts.values()) max = Math.max(max, count)
  return max
}
