import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useUser } from '../context/UserContext'
import styles from './Admin.module.css'

type Tab = 'overview'|'users'|'billing'|'withdrawals'|'errors'|'audit'|'system'
const labels: Record<Tab,string> = {overview:'Übersicht',users:'Nutzer',billing:'Billing',withdrawals:'Widerrufe',errors:'Fehlerfälle',audit:'Audit Log',system:'System'}

async function adminFetch(path:string, options?:RequestInit) {
  const token=localStorage.getItem('academy.token')
  const res=await fetch(`/api/admin${path}`,{...options,headers:{...(options?.body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})}})
  if(!res.ok){const error:any=new Error((await res.json().catch(()=>null))?.detail||`Request failed (${res.status})`);error.status=res.status;throw error}
  return res.json()
}
const val=(v:any)=>v===null||v===undefined||v===''?'–':String(v)
const date=(v:any)=>v?new Date(v).toLocaleString('de-DE'):'–'

export default function Admin(){
  const {user}=useUser(); const [allowed,setAllowed]=useState<boolean|null>(null); const [tab,setTab]=useState<Tab>('overview');
  const [data,setData]=useState<any>(null); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const [detail,setDetail]=useState<any>(null); const [busy,setBusy]=useState('')
  useEffect(()=>{if(!user){setAllowed(null);return} adminFetch('/me').then(()=>setAllowed(true)).catch(e=>setAllowed(e.status===403?false:null))},[user])
  useEffect(()=>{if(!allowed)return;setError('');setData(null);setDetail(null);const paths:any={overview:'/overview',billing:'/billing/issues',withdrawals:'/withdrawals',errors:'/errors',audit:'/audit',system:'/system/status'};if(tab!=='users')adminFetch(paths[tab]).then(setData).catch(e=>setError(e.message))},[allowed,tab])
  if(!user)return <section className={styles.center}><h1>Admin</h1><p>Bitte melde dich über den bestehenden rInQ-Login an.</p><Link className={styles.primary} to="/?next=/admin">Zum Login</Link></section>
  if(allowed===null)return <section className={styles.center}><p>Zugriff wird geprüft …</p></section>
  if(!allowed)return <section className={styles.center}><h1>Kein Zugriff</h1><p>Dieser Bereich ist nur für Administratoren verfügbar.</p></section>
  const search=async(e:React.FormEvent)=>{e.preventDefault();setError('');setData(null);try{setData(await adminFetch(`/users/search?q=${encodeURIComponent(query)}`))}catch(e:any){setError(e.message)}}
  const act=async(key:string,path:string,message:string)=>{if(!confirm(message))return;setBusy(key);setError('');try{await adminFetch(path,{method:'POST',body:'{}'});alert('Aktion erfolgreich abgeschlossen.');if(detail?.account?.rinq_user_id)setDetail(await adminFetch(`/users/${detail.account.rinq_user_id}`));else setData(await adminFetch('/withdrawals'))}catch(e:any){setError(e.message)}finally{setBusy('')}}
  return <section className={styles.page}>
    <header><p className={styles.eyebrow}>Betrieb & Support</p><h1>Admin</h1></header>
    <nav className={styles.nav} aria-label="Admin-Bereiche">{(Object.keys(labels) as Tab[]).map(k=><button type="button" key={k} className={tab===k?styles.active:''} onClick={()=>setTab(k)}>{labels[k]}</button>)}</nav>
    {error&&<div className={styles.error}>{error}</div>}
    {tab==='overview'&&data&&<div className={styles.cards}>{[['Nutzer',data.users],['Aktive Premium-Abos',data.active_premium],['Offene Widerrufe',data.open_withdrawals],['Manual Review',data.manual_review],['Fehlgeschlagene Mails',data.failed_mails],['Billing-Probleme',data.billing_issues]].map(([k,v])=><article className={styles.card} key={k}><span>{k}</span><strong>{val(v)}</strong></article>)}</div>}
    {tab==='users'&&<UsersPanel query={query} setQuery={setQuery} data={data} detail={detail} busy={busy} search={search} setDetail={setDetail} setError={setError} act={act}/>} 
    {tab==='billing'&&data&&<AdminTable rows={data.issues}/>} 
    {tab==='withdrawals'&&data&&<WithdrawalTable rows={data.withdrawals||[]} busy={busy} act={act}/>} 
    {tab==='errors'&&data&&<ErrorTable rows={data.errors||[]} openUser={async(id:string)=>{setTab('users');setDetail(await adminFetch(`/users/${id}`))}}/>} 
    {tab==='audit'&&data&&<AuditTable rows={data.entries||[]}/>} 
    {tab==='system'&&data&&<SystemPanel data={data}/>}
    {!data&&tab!=='users'&&!error&&<p>Lädt …</p>}
  </section>
}
function UsersPanel({query,setQuery,data,detail,busy,search,setDetail,setError,act}:any){
  const users=Array.isArray(data?.users)?data.users:[]
  const openUser=async(userId:string)=>{setError('');try{setDetail(await adminFetch(`/users/${userId}`))}catch(e:any){setError(e?.message||'Nutzerdetails konnten nicht geladen werden')}}
  return <section aria-labelledby="admin-users-title"><h2 id="admin-users-title">Nutzersuche</h2><p>Suche datensparsam nach Support-Code, interner User-ID, Login-ID oder Stripe Customer/Subscription ID. E-Mail-Adressen werden nicht durchsucht.</p><form className={styles.search} onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Support-Code, User-ID oder Stripe-ID" required/><button type="submit">Suchen</button></form>{data&&users.length===0&&<p>Keine Nutzer gefunden.</p>}{users.length>0&&<div className={styles.tableWrap}><table><thead><tr><th>Nutzer</th><th>User-ID</th><th>Status</th><th>Stripe</th></tr></thead><tbody>{users.map((u:any)=><tr key={u.rinq_user_id}><td><button type="button" className={styles.userLink} onClick={()=>openUser(u.rinq_user_id)}>{val(u.display_name||u.legacy_username)}</button></td><td><code>{u.rinq_user_id}</code></td><td>{u.status}</td><td>{val(u.external_customer_id)}</td></tr>)}</tbody></table></div>}{detail?.account&&<article className={styles.detail}><h2>{val(detail.account.display_name||detail.account.legacy_username)}</h2><dl><dt>User-ID</dt><dd><code>{detail.account.rinq_user_id}</code></dd><dt>Registriert</dt><dd>{date(detail.account.created_at)}</dd><dt>Loginanbieter</dt><dd>{Array.isArray(detail.account.providers)?detail.account.providers.map((p:any)=>p.provider).join(', ')||'–':'–'}</dd><dt>Accountstatus</dt><dd>{val(detail.account.status)}</dd><dt>Sessions</dt><dd>{val(detail.progress?.completed)} abgeschlossen / {val(detail.progress?.total)} gesamt</dd><dt>Letzter Save</dt><dd>{date(detail.progress?.last_save)}</dd></dl><h3>Billing</h3>{Array.isArray(detail.billing)&&detail.billing.length?detail.billing.map((b:any)=><div className={styles.sub} key={b.external_subscription_id}><code>{b.external_subscription_id}</code><span>{b.status} · {val(b.price_id)} · bis {date(b.current_period_end)}</span></div>):<p>Kein Abo gespeichert.</p>}<button type="button" disabled={!!busy} onClick={()=>act('sync',`/users/${detail.account.rinq_user_id}/resync-entitlement`,'Stripe wird serverseitig abgefragt und der lokale Premiumstatus neu berechnet. Fortfahren?')}>Premiumstatus neu synchronisieren</button></article>}</section>
}
function ErrorTable({rows,openUser}:{rows:any[],openUser:(id:string)=>void}){return <div className={styles.tableWrap}><table><thead><tr><th>Zeit</th><th>Typ</th><th>Interne User-ID</th><th>Referenz</th><th>Status / Ursache</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.type+'-'+r.reference}><td>{date(r.occurred_at)}</td><td>{r.type}</td><td>{r.rinq_user_id?<button type="button" className={styles.userLink} onClick={()=>openUser(r.rinq_user_id)}>{r.rinq_user_id}</button>:'–'}</td><td><code>{r.reference}</code></td><td>{val(r.status)}<br/><small>{val(r.cause)}</small></td></tr>)}</tbody></table>{!rows.length&&<p className={styles.empty}>Keine offenen operativen Fehler gefunden.</p>}</div>}
function AuditTable({rows}:{rows:any[]}){return <div className={styles.tableWrap}><table><thead><tr><th>Zeit</th><th>Admin-ID</th><th>Aktion</th><th>Zielreferenz</th><th>Ergebnis</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{date(r.created_at)}</td><td><code>{r.admin_user_id}</code></td><td>{r.action}</td><td><code>{r.target_reference}</code></td><td>{r.result}</td></tr>)}</tbody></table>{!rows.length&&<p className={styles.empty}>Noch keine sensiblen Admin-Aktionen protokolliert.</p>}</div>}
function SystemPanel({data}:{data:any}){const rows=[['Umgebung',data.environment],['App-Version',data.app_version],['Git Commit',data.git_commit],['Speicher',data.storage],['Datenbank erreichbar',data.database_reachable?'Ja':'Nein'],['Stripe konfiguriert',data.stripe_configured?'Ja':'Nein'],['SMTP konfiguriert',data.smtp_configured?'Ja':'Nein'],['Letzte Transaktionsmail',date(data.last_transactional_mail)],['Fehlgeschlagene Mails',data.failed_mails],['Letzter erfolgreicher Stripe-Webhook',data.last_stripe_webhook?data.last_stripe_webhook.event_type+' · '+date(data.last_stripe_webhook.at):'–'],['Webhook-Fehlerhistorie',data.webhook_failure_history_available?'Verfügbar':'Noch nicht persistiert']];return <article className={styles.detail}><h2>Systemstatus</h2><p>SMTP ist der konfigurierte Versandweg für transaktionale E-Mails wie Widerrufs- und Erstattungsbestätigungen.</p><dl>{rows.map(([k,v])=><div key={String(k)}><dt>{k}</dt><dd>{val(v)}</dd></div>)}</dl></article>}
function AdminTable({rows}:{rows:any[]}){return <div className={styles.tableWrap}><table><thead><tr><th>User</th><th>Subscription</th><th>Stripe</th><th>Lokal</th><th>Aktualisiert</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.external_subscription_id}><td><code>{r.rinq_user_id}</code></td><td>{r.external_subscription_id}</td><td>{r.stripe_status}</td><td>{val(r.local_status)}</td><td>{date(r.updated_at)}</td></tr>)}</tbody></table>{!rows.length&&<p>Keine Probleme gefunden.</p>}</div>}
function WithdrawalTable({rows,busy,act}:{rows:any[],busy:string,act:(k:string,p:string,m:string)=>void}){return <div className={styles.tableWrap}><table><thead><tr><th>Eingang</th><th>Nutzer</th><th>Status</th><th>Refund / Mail</th><th>Fehler</th><th>Aktionen</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{date(r.received_at)}<br/><code>{r.id}</code></td><td><code>{val(r.rinq_user_id)}</code><br/><small>{r.contact_email_present?'Kontaktadresse im Vorgang vorhanden':'Keine Kontaktadresse im Vorgang'}</small></td><td>{r.status}</td><td>{r.refund_status} / {r.email_status}</td><td>{val(r.failure_reason)}</td><td className={styles.actions}><button disabled={!!busy||r.email_status==='sent'} onClick={()=>act(r.id+'mail',`/withdrawals/${r.id}/retry-email`,'Bestätigungsmail für diesen bestehenden Widerruf erneut senden?')}>Mail erneut</button><button disabled={!!busy||!['manual_review','refund_pending','received'].includes(r.status)} onClick={()=>act(r.id+'process',`/withdrawals/${r.id}/retry-processing`,'Die idempotente Widerrufsverarbeitung inklusive exakter Zahlungserstattung erneut ausführen?')}>Verarbeitung erneut</button><button disabled={!!busy||!!r.premium_revoked_at} onClick={()=>act(r.id+'revoke',`/withdrawals/${r.id}/retry-premium-revoke`,'Premiumberechtigung für diesen Widerruf erneut entziehen?')}>Premium entziehen</button></td></tr>)}</tbody></table>{!rows.length&&<p>Keine Vorgänge gefunden.</p>}</div>}
