import type { CosmeticDefinition } from '../types'
import { MASTERY_COIN_IDS } from '../mastery/masteryCatalog'

/** Phase-2 collectibles: stickers, frames, coins, shop items, collection rewards, stick/puck stubs. */
export const PHASE2_COSMETICS: CosmeticDefinition[] = [
  // --- Collection / achievement exclusives ---
  {
    id: 'emblem_slot_resident',
    type: 'emblem',
    name: 'Slot Resident',
    flavorText: 'Rent is due. He’s still not leaving.',
    rarity: 'rare',
    assetId: 'emblem_crease_01',
    collectionId: 'the_slot',
    origin: { type: 'achievement', achievementId: 'slot_squatter' },
  },
  {
    id: 'frame_slot',
    type: 'frame',
    name: 'Slot Frame',
    flavorText: 'Dangerous square. Soft edges. Sitzt um die Account-Pille.',
    rarity: 'uncommon',
    collectionId: 'the_slot',
    origin: { type: 'achievement', achievementId: 'getting_warm' },
    metadata: { cssClass: 'frame-slot' },
  },
  {
    id: 'sticker_slot',
    type: 'sticker',
    name: 'Slot Sticker',
    flavorText: 'No rent. No problem.',
    rarity: 'common',
    collectionId: 'the_slot',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'banner_property_of_the_slot',
    type: 'banner',
    name: 'Property of the Slot',
    flavorText: 'Trespassers will be analyzed.',
    rarity: 'rare',
    assetId: 'banner_crease_01',
    collectionId: 'the_slot',
    origin: { type: 'collection', collectionId: 'the_slot' },
  },
  {
    id: 'emblem_blue_line_inspector',
    type: 'emblem',
    name: 'Blue Line Inspector',
    flavorText: 'Clipboard optional.',
    rarity: 'rare',
    assetId: 'emblem_blue_line_01',
    collectionId: 'blue_line_department',
    origin: { type: 'achievement', achievementId: 'blue_line_inspector' },
  },
  {
    id: 'sticker_entry',
    type: 'sticker',
    name: 'Entry Sticker',
    flavorText: 'Feet first? Brain first.',
    rarity: 'common',
    collectionId: 'blue_line_department',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'sticker_exit',
    type: 'sticker',
    name: 'Exit Sticker',
    flavorText: 'Clear under pressure.',
    rarity: 'common',
    collectionId: 'blue_line_department',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'banner_blue_line_wizard',
    type: 'banner',
    name: 'Blue Line Wizard',
    flavorText: 'Corridor magic.',
    rarity: 'epic',
    assetId: 'banner_blue_line_01',
    collectionId: 'blue_line_department',
    origin: { type: 'collection', collectionId: 'blue_line_department' },
  },
  {
    id: 'sticker_tape',
    type: 'sticker',
    name: 'Tape Sticker',
    flavorText: 'Tape-to-tape energy.',
    rarity: 'common',
    collectionId: 'rink_rat_starter',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'frame_rink_rat',
    type: 'frame',
    name: 'Rink Rat Frame',
    flavorText: 'Always somewhere at the glass. Liegt um PUX, Avatar und Logout.',
    rarity: 'rare',
    collectionId: 'rink_rat_starter',
    origin: { type: 'collection', collectionId: 'rink_rat_starter' },
    metadata: { cssClass: 'frame-rink-rat' },
  },
  {
    id: 'emblem_goblin',
    type: 'emblem',
    name: 'Goblin Emblem',
    flavorText: 'Neutral zone chaos agent.',
    rarity: 'uncommon',
    assetId: 'emblem_puck_01',
    collectionId: 'neutral_zone_goblins',
    origin: { type: 'achievement', achievementId: 'neutral_zone_tourist' },
  },
  {
    id: 'sticker_watch_the_center',
    type: 'sticker',
    name: 'Watch The Center',
    flavorText: 'Eyes on the middle first.',
    rarity: 'uncommon',
    collectionId: 'neutral_zone_goblins',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'banner_neutral_zone_goblin_shop',
    type: 'banner',
    name: 'Neutral Zone Goblin',
    flavorText: 'Just browsing between the blues.',
    rarity: 'uncommon',
    assetId: 'banner_neutral_01',
    collectionId: 'neutral_zone_goblins',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'banner_neutral_zone_goblin_legend',
    type: 'banner',
    name: 'Neutral Zone Goblin (Legendary)',
    flavorText: 'Collection complete. Goblin ascended.',
    rarity: 'legendary',
    assetId: 'banner_chalk_01',
    collectionId: 'neutral_zone_goblins',
    origin: { type: 'collection', collectionId: 'neutral_zone_goblins' },
    visibility: 'silhouette',
  },

  // --- Mastery coins ---
  {
    id: MASTERY_COIN_IDS.defensive_zone,
    type: 'masteryCoin',
    name: 'Defensive Zone Coin',
    flavorText: 'Structure before panic.',
    rarity: 'epic',
    origin: { type: 'track_mastery', trackId: 'D2' },
  },
  {
    id: MASTERY_COIN_IDS.neutral_zone,
    type: 'masteryCoin',
    name: 'Neutral Zone Coin',
    flavorText: 'Own the middle third.',
    rarity: 'epic',
    origin: { type: 'track_mastery', trackId: 'C2' },
  },
  {
    id: MASTERY_COIN_IDS.offensive_zone,
    type: 'masteryCoin',
    name: 'Offensive Zone Coin',
    flavorText: 'Pressure with purpose.',
    rarity: 'epic',
    origin: { type: 'track_mastery', trackId: 'C3' },
    visibility: 'silhouette',
  },
  {
    id: MASTERY_COIN_IDS.powerplay,
    type: 'masteryCoin',
    name: 'Powerplay Coin',
    flavorText: 'Man advantage, brain advantage.',
    rarity: 'epic',
    origin: { type: 'achievement', achievementId: 'powerplay_regular' },
  },
  {
    id: MASTERY_COIN_IDS.penalty_kill,
    type: 'masteryCoin',
    name: 'Penalty Kill Coin',
    flavorText: 'Survive. Clear. Breathe.',
    rarity: 'epic',
    origin: { type: 'achievement', achievementId: 'pk_regular' },
  },
  {
    id: MASTERY_COIN_IDS.entries_clears,
    type: 'masteryCoin',
    name: 'Entries & Clears Coin',
    flavorText: 'Blue line traffic controller.',
    rarity: 'epic',
    origin: { type: 'track_mastery', trackId: 'D3' },
  },

  // --- Shop exclusives ---
  {
    id: 'title_shop_film_room',
    type: 'title',
    name: 'Film Room',
    text: 'Film Room',
    rarity: 'common',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'title_shop_bench_boss',
    type: 'title',
    name: 'Bench Boss',
    text: 'Bench Boss',
    rarity: 'uncommon',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'title_shop_glass_leaner',
    type: 'title',
    name: 'Glass Leaner',
    text: 'Glass Leaner',
    rarity: 'common',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'title_shop_quiet_observer',
    type: 'title',
    name: 'Quiet Observer',
    text: 'Quiet Observer',
    rarity: 'common',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'tagline_shop_pause_culture',
    type: 'tagline',
    name: 'Pause Culture',
    text: 'Pause culture.',
    rarity: 'common',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'tagline_shop_read_the_ice',
    type: 'tagline',
    name: 'Read The Ice',
    text: 'Read the ice.',
    rarity: 'common',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'tagline_shop_structure_lite',
    type: 'tagline',
    name: 'Structure Lite',
    text: 'Structure > highlight.',
    rarity: 'common',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'emblem_shop_simple_crest',
    type: 'emblem',
    name: 'Simple Crest',
    rarity: 'uncommon',
    assetId: 'emblem_rink_01',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'emblem_shop_chalk',
    type: 'emblem',
    name: 'Chalk Mark',
    rarity: 'uncommon',
    assetId: 'emblem_arrow_01',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'banner_shop_soft_ice',
    type: 'banner',
    name: 'Soft Ice',
    rarity: 'uncommon',
    assetId: 'banner_neutral_01',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'banner_shop_night_rink',
    type: 'banner',
    name: 'Night Rink',
    rarity: 'rare',
    assetId: 'banner_chalk_01',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'frame_shop_basic',
    type: 'frame',
    name: 'Basic Frame',
    flavorText: 'Sauberer Stahlring um die Account-Pille.',
    rarity: 'common',
    origin: { type: 'pux_shop' },
    metadata: { cssClass: 'frame-basic' },
  },
  {
    id: 'frame_shop_rare_trim',
    type: 'frame',
    name: 'Rare Trim Frame',
    flavorText: 'Gold-Teal-Doppelkante. Schon laut.',
    rarity: 'rare',
    origin: { type: 'pux_shop' },
    metadata: { cssClass: 'frame-rare' },
  },
  {
    id: 'avatar_tape_01',
    type: 'avatar',
    name: 'Tape Roll',
    flavorText: 'Grün. Acht Ecken. Immer kleben.',
    rarity: 'uncommon',
    assetId: 'avatar_tape_01',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'avatar_blueline_01',
    type: 'avatar',
    name: 'Blue Line Mark',
    flavorText: 'Blau. Sechseck. Entries ernst.',
    rarity: 'rare',
    assetId: 'avatar_blueline_01',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'avatar_slot_01',
    type: 'avatar',
    name: 'The Slot',
    flavorText: 'Violett. Raute. Wohnen im gefährlichen Quadrat.',
    rarity: 'epic',
    assetId: 'avatar_slot_01',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'avatar_goldpuck_01',
    type: 'avatar',
    name: 'Gold Puck',
    flavorText: 'Gold. Zackiger Stern. Der Puck hat Miete gezahlt.',
    rarity: 'legendary',
    assetId: 'avatar_goldpuck_01',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'avatar_aurora_01',
    type: 'avatar',
    name: 'Aurora Ice',
    flavorText: 'Pink. Stern. Nachtschicht auf dem Eis.',
    rarity: 'mythic',
    assetId: 'avatar_aurora_01',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'title_night_circuit',
    type: 'title',
    name: 'After Hours',
    text: 'After Hours',
    flavorText: 'Die Rink macht um 2 zu. Du nicht.',
    rarity: 'mythic',
    collectionId: 'night_circuit',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'avatar_night_circuit',
    type: 'avatar',
    name: 'Circuit Face',
    flavorText: 'Visor an. Grid an. Mythic-Stern in Magenta.',
    rarity: 'mythic',
    assetId: 'avatar_night_circuit',
    collectionId: 'night_circuit',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'banner_night_circuit',
    type: 'banner',
    name: 'Neon District',
    flavorText: 'Raster, Neon, keine Pause. Oben rechts und unten links frei.',
    rarity: 'mythic',
    assetId: 'banner_night_circuit',
    collectionId: 'night_circuit',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'emblem_night_circuit',
    type: 'emblem',
    name: 'Grid Crest',
    flavorText: 'Ein Knoten im Circuit. Sitzt oben rechts auf der Karte.',
    rarity: 'mythic',
    assetId: 'emblem_night_circuit',
    collectionId: 'night_circuit',
    origin: { type: 'pux_shop' },
  },
  {
    id: 'tagline_stay_on_the_grid',
    type: 'tagline',
    name: 'Stay on the Grid',
    text: 'Stay on the grid.',
    flavorText: 'Collection complete. Der Circuit kennt deinen Namen.',
    rarity: 'mythic',
    collectionId: 'night_circuit',
    origin: { type: 'collection', collectionId: 'night_circuit' },
  },
  {
    id: 'frame_ice_legend',
    type: 'frame',
    name: 'Ice Legend',
    flavorText: 'Rotierendes Eisgold. Die Pille bekommt eine eigene Show.',
    rarity: 'legendary',
    origin: { type: 'pux_shop' },
    metadata: { cssClass: 'frame-legend' },
  },
  {
    id: 'frame_night_circuit',
    type: 'frame',
    name: 'Night Circuit',
    flavorText: 'Kein Soft-Pill. HUD-Schnitt, Brackets, Nachtschicht.',
    rarity: 'mythic',
    collectionId: 'night_circuit',
    origin: { type: 'pux_shop' },
    metadata: { cssClass: 'frame-mythic' },
  },

  // --- Mastery titles ---
  {
    id: 'title_c1_obsessed',
    type: 'title',
    name: 'C1 Obsessed',
    text: 'C1 Obsessed',
    rarity: 'rare',
    origin: { type: 'track_mastery', trackId: 'C1' },
  },
  {
    id: 'title_nz_obsessed',
    type: 'title',
    name: 'NZ Obsessed',
    text: 'NZ Obsessed',
    rarity: 'rare',
    origin: { type: 'track_mastery', trackId: 'C2' },
  },
  {
    id: 'title_blue_line_obsessed',
    type: 'title',
    name: 'Blue Line Obsessed',
    text: 'Blue Line Obsessed',
    rarity: 'epic',
    origin: { type: 'track_mastery', trackId: 'D3' },
  },
  {
    id: 'title_drill_obsessed',
    type: 'title',
    name: 'Drill Obsessed',
    text: 'Drill Obsessed',
    rarity: 'rare',
    origin: { type: 'achievement', achievementId: 'same_drill_ten' },
  },
  {
    id: 'sticker_matchday_first_read',
    type: 'sticker',
    name: 'First Read',
    flavorText: 'Prototype Matchday Moment. Heute das Spiel, heute der Read.',
    rarity: 'uncommon',
    collectionId: 'matchday_moments',
    origin: { type: 'challenge', challengeId: 'challenge_matchday_tonights_read' },
  },
  {
    id: 'puck_wasteland_scrap',
    type: 'puckModel',
    name: 'Scrap Puck',
    flavorText: 'Kein Standard-Vulcanized. Stahlringe, Rost, eine Seriennummer die niemand mehr pflegt.',
    description: 'Wasteland collectible. Prototype SVG art.',
    rarity: 'rare',
    collectionId: 'wasteland',
    origin: { type: 'challenge', challengeId: 'challenge_collection_survive_the_shift' },
  },

  // --- Stick / Puck foundation (no 3D yet) ---
  {
    id: 'stick_model_composite_01',
    type: 'stickModel',
    name: 'Composite 01',
    description: 'Standard composite stick. 3D viewer comes in Phase 2.5.',
    rarity: 'common',
    origin: { type: 'starter' },
    visibility: 'visible',
    metadata: { previewOnly: true },
  },
  {
    id: 'puck_model_standard_01',
    type: 'puckModel',
    name: 'Standard Puck',
    description: 'Legacy stub — use Classic Puck (3D PoC) for the viewer.',
    rarity: 'common',
    origin: { type: 'starter' },
    visibility: 'visible',
    metadata: { previewOnly: true, supersededBy: 'puck_model_classic' },
  },
  {
    id: 'stick_skin_black_ice',
    type: 'stickSkin',
    name: 'Black Ice',
    flavorText: 'Looks fast even when paused.',
    rarity: 'epic',
    origin: { type: 'achievement', achievementId: 'blue_line_inspector' },
    visibility: 'silhouette',
    metadata: { compatibleModelIds: ['stick_model_composite_01'], previewOnly: true },
  },
  {
    id: 'puck_skin_slot_goblin',
    type: 'puckSkin',
    name: 'Slot Goblin',
    flavorText: 'Just one more scene.',
    rarity: 'rare',
    origin: { type: 'achievement', achievementId: 'clip_goblin' },
    visibility: 'silhouette',
    metadata: { compatibleModelIds: ['puck_model_standard_01'], previewOnly: true },
  },
]
